# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='biografia',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='telefone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profissao',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skype',
            field=models.CharField(default='', max_length=100),
        ),
    ]
