# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170618_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biografia',
            field=models.CharField(default=b'', max_length=250),
        ),
    ]
