# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170620_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='biografia',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profissao',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skype',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telefone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
