# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20170621_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
