# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='habilidades',
            field=models.ManyToManyField(blank=True, to='core.Area'),
        ),
    ]
