# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='exibir_perfil',
            field=models.BooleanField(default=True),
        ),
    ]
