# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_post_exibir_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(max_length=250),
        ),
    ]
