# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170622_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='exibir_perfil',
        ),
    ]
