# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20170622_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='area',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
